# Generated by Django 3.0.7 on 2020-06-28 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.CharField(max_length=50)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Departamento')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Departamento')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadPruebas', models.IntegerField()),
                ('cantidadPositivas', models.IntegerField()),
                ('sospechosos', models.IntegerField()),
                ('fechaTomada', models.DateField()),
                ('cantFemenino', models.IntegerField()),
                ('cantMasculino', models.IntegerField()),
                ('edadCero', models.IntegerField()),
                ('edadDiez', models.IntegerField()),
                ('edadVeinte', models.IntegerField()),
                ('edadCuarenta', models.IntegerField()),
                ('edadSesenta', models.IntegerField()),
                ('edadOchenta', models.IntegerField()),
                ('estado', models.IntegerField(default=1)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Departamento')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Direccion')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Municipio')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
    ]
